import type { Metadata } from "next";
import { Logo } from "@/components/Logo";

export const metadata: Metadata = {
  title: "Privacy policy",
  description: "How Guardian handles documents, tokens, and personal information.",
  alternates: { canonical: "https://guardiancompliance.app/privacy" },
};

const EFFECTIVE_DATE = "April 17, 2026";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-[#f0f4fa] via-white to-[#e8edf5]">
      <header className="border-b border-blue-100/30 bg-white/80 backdrop-blur-xl sticky top-0 z-10">
        <div className="max-w-3xl mx-auto px-6 py-3 flex items-center justify-between">
          <Logo subtitle="Privacy" />
          <a href="mailto:fretin13@gmail.com" className="text-xs font-semibold text-[#3a5a8c] hover:text-[#1a2036]">
            Questions →
          </a>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <div className="text-[10px] uppercase tracking-[0.18em] text-[#8b97ad] mb-2">Effective {EFFECTIVE_DATE}</div>
        <h1 className="text-3xl font-bold text-[#0d1424] mb-4">Privacy policy</h1>
        <p className="text-sm text-[#556480] leading-relaxed mb-10 max-w-2xl">
          Guardian handles sensitive immigration and tax documents — SSN, passport numbers, EINs,
          lease agreements, tax returns. This page describes exactly what we collect, where it lives,
          who else touches it, and what you can ask us to do with it.
        </p>

        <Section title="1. What we collect">
          <p>
            <strong>Account data:</strong> email, password hash (bcrypt), timestamps of sign-in. Mixpanel
            analytics event on page load (anonymized visitor ID; de-anonymized only after you sign in).
          </p>
          <p>
            <strong>Documents you upload:</strong> PDFs, images, text files, CSVs placed in your data
            room. Full content is stored — we extract text server-side (or locally via the MCP server
            when you use Claude Code / Desktop / Codex) for classification and retrieval.
          </p>
          <p>
            <strong>Extracted facts:</strong> doc type, dates, form numbers, counterparties, amounts.
            Scoped to your account.
          </p>
          <p>
            <strong>Compliance checks:</strong> findings, deadlines, risks derived from your documents.
            Scoped to your account.
          </p>
          <p>
            <strong>Gmail access (optional):</strong> if you connect Gmail through the MCP server
            (`gmail_*` tools), Guardian uses Google OAuth2 with the scopes <code>gmail.readonly</code>,{" "}
            <code>gmail.compose</code>, <code>gmail.modify</code>. Messages are read on demand by your
            local MCP process; Guardian servers never see Gmail content unless you explicitly upload it
            via the tools.
          </p>
        </Section>

        <Section title="2. Where your data lives">
          <p>
            <strong>Application host:</strong> Fly.io (SOC 2 Type II, 2024). Data is stored on an
            encrypted persistent volume in the <code>ewr</code> (US East) region.
          </p>
          <p>
            <strong>Database:</strong> PostgreSQL. For early deployments this is SQLite on the Fly
            volume; production paths use Neon Postgres (SOC 2 Type II, AES-256 at rest, TLS in transit).
          </p>
          <p>
            <strong>Vector index (RAG):</strong> ChromaDB, stored on the same encrypted volume.
            Embeddings are generated by OpenAI&apos;s embedding API and contain a compressed numeric
            representation of document chunks.
          </p>
          <p>
            <strong>Local data (MCP):</strong> when you use the MCP server, document parsing runs
            on your device. Files you do not explicitly upload stay on your device.
          </p>
        </Section>

        <Section title="3. Sub-processors">
          <p>Guardian uses the following third parties to deliver the service:</p>
          <ul className="list-disc pl-5 space-y-1.5 my-3">
            <li><strong>Fly.io</strong> — application hosting, storage volumes, TLS termination</li>
            <li><strong>Neon</strong> — managed Postgres (production tier)</li>
            <li><strong>Anthropic</strong> — Claude API, used when you ask compliance questions or generate correspondence</li>
            <li><strong>OpenAI</strong> — embeddings (RAG index) and occasional reasoning / tool calls</li>
            <li><strong>Google</strong> — Gmail API (only if you connect it)</li>
            <li><strong>Mixpanel</strong> — product analytics (page views, feature usage). No document content is sent.</li>
          </ul>
          <p>
            Sub-processors receive only the minimum data required for the operation you invoke. LLM
            prompts include document text only when you request a check or question that needs it.
          </p>
        </Section>

        <Section title="4. How we use your data">
          <p>We use your data only to:</p>
          <ul className="list-disc pl-5 space-y-1.5 my-3">
            <li>Run compliance checks and cross-references you request</li>
            <li>Generate forms (Form 8843, 1040-NR, FBAR, 5472, I-983) and mailing kits</li>
            <li>Answer your questions about your own documents</li>
            <li>Share a case package with a collaborator you explicitly designate (via share tokens)</li>
            <li>Improve the product — aggregated, non-PII metrics only</li>
          </ul>
          <p>
            We do <strong>not</strong> sell your data. We do <strong>not</strong> use it to train
            third-party models. We do <strong>not</strong> read it for advertising.
          </p>
        </Section>

        <Section title="5. Authentication tokens">
          <p>
            The <code>gdn_oc_*</code> API tokens you generate at <a href="/connect" className="text-[#3a5a8c] underline">/connect</a> are
            stored as SHA-256 hashes. Raw token values are shown to you once at creation and never
            persisted in plaintext. You can rotate or revoke at any time from the same page.
          </p>
          <p>
            Data-room share tokens are short-lived, scope-limited JWTs (HMAC-SHA256). They embed only
            the case folder path, recipient label, and expiry (default 14 days, configurable). They do
            not grant write access.
          </p>
        </Section>

        <Section title="6. Retention">
          <p>
            <strong>Uploaded documents:</strong> kept until you delete them from your data room or close
            your account.
          </p>
          <p>
            <strong>Analytics events:</strong> kept for 12 months then aggregated.
          </p>
          <p>
            <strong>Backups:</strong> encrypted database backups held for 30 days then destroyed.
          </p>
          <p>
            <strong>Deleted accounts:</strong> purged from the production database within 30 days;
            purged from backups on normal backup rotation.
          </p>
        </Section>

        <Section title="7. Your rights">
          <p>You can:</p>
          <ul className="list-disc pl-5 space-y-1.5 my-3">
            <li><strong>Access</strong> any data we hold about you — email the address below</li>
            <li><strong>Export</strong> everything as a zip — use the <code>download-all</code> feature on your data-room share page</li>
            <li><strong>Delete</strong> individual documents from the data room</li>
            <li><strong>Revoke</strong> MCP / OpenClaw tokens from <a href="/connect" className="text-[#3a5a8c] underline">/connect</a></li>
            <li><strong>Revoke</strong> outstanding share tokens (rotate the JWT secret; see the email address below)</li>
            <li><strong>Delete your account</strong> — email us; full deletion within 30 days</li>
          </ul>
          <p>
            If you are in the EU, UK, California, or a jurisdiction with specific data-subject rights
            (GDPR, UK-GDPR, CCPA), the above satisfies your rights of access, portability, erasure, and
            objection.
          </p>
        </Section>

        <Section title="8. Security">
          <p>
            In transit, Guardian uses TLS 1.3. At rest, volumes and databases are AES-256 encrypted.
            Access to production is limited to the project maintainer via Fly.io SSH (SSH key auth, no
            passwords). API authentication uses Bearer tokens hashed with SHA-256 before storage.
          </p>
          <p>
            We do not have independent SOC 2 certification as of this date — the decision log records
            why and under what conditions that changes. Our infrastructure providers (Fly.io, Neon) do.
          </p>
          <p>
            If you discover a security issue, please email us <strong>before</strong> disclosing
            publicly. We will respond within 48 hours and coordinate disclosure.
          </p>
        </Section>

        <Section title="9. Children">
          <p>
            Guardian is not intended for users under 13. If you believe a child has created an
            account, contact us and we will delete it.
          </p>
        </Section>

        <Section title="10. Changes to this policy">
          <p>
            Material changes will be announced on this page with a new effective date. You will be
            notified by email at least 14 days before a change that narrows your rights or expands our
            data use.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            Policy questions, data subject requests, account deletion, security disclosures:{" "}
            <a href="mailto:fretin13@gmail.com" className="text-[#3a5a8c] underline">
              fretin13@gmail.com
            </a>
            .
          </p>
          <p className="text-[11px] text-[#8b97ad] mt-4">
            Source of truth for this policy:{" "}
            <a
              href="https://github.com/LEE-CHENYU/compliance-os/blob/main/frontend/src/app/privacy/page.tsx"
              className="underline underline-offset-2"
            >
              github.com/LEE-CHENYU/compliance-os
            </a>
            .
          </p>
        </Section>

        <footer className="text-[11px] text-[#a6b0c5] py-10 border-t border-blue-100/30 mt-10 text-center">
          Effective {EFFECTIVE_DATE} · Guardian
        </footer>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-base font-semibold text-[#0d1424] mb-3">{title}</h2>
      <div className="text-sm text-[#556480] leading-relaxed space-y-3 [&_code]:bg-blue-50 [&_code]:text-[#3a5a8c] [&_code]:px-1 [&_code]:rounded [&_code]:text-[12px] [&_code]:font-mono">
        {children}
      </div>
    </section>
  );
}
