export type GraphEdgeRisk = "safe" | "mutating" | "external" | "payment" | "voice";

export type GraphFailureKey =
  | "auth-login"
  | "auth-register"
  | "dashboard-timeline"
  | "dashboard-stats"
  | "dashboard-documents"
  | "dashboard-openclaw-connection"
  | "dashboard-openclaw-token"
  | "dashboard-upload-prepare"
  | "dashboard-upload-submit"
  | "dashboard-upload-quota"
  | "dashboard-document-open"
  | "dashboard-chat"
  | "dashboard-form-fill-extract"
  | "dashboard-form-fill-generate"
  | "services-list"
  | "service-detail"
  | "service-start-order"
  | "questionnaire-load"
  | "questionnaire-evaluate"
  | "questionnaire-order"
  | "find-lawyer-prefill"
  | "find-lawyer-submit"
  | "professional-search-status"
  | "professional-search-track"
  | "professional-search-download"
  | "professional-search-paid"
  | "professional-search-checkout"
  | "professional-search-claim"
  | "professional-search-trial"
  | "case-load"
  | "case-gmail-connect"
  | "case-gmail-sync"
  | "case-gmail-disconnect"
  | "case-engagement-add"
  | "case-engagement-update"
  | "case-engagement-delete"
  | "case-engagement-draft-email"
  | "case-document-upload"
  | "case-document-update"
  | "case-document-delete"
  | "attorney-dashboard"
  | "attorney-case"
  | "attorney-review"
  | "account-orders"
  | "order-detail"
  | "order-prefill"
  | "order-save-intake"
  | "order-process"
  | "order-mark-mailed"
  | "agreement-load"
  | "agreement-sign"
  | "form8843-generate"
  | "form8843-success"
  | "form8843-download"
  | "form8843-mark-mailed"
  | "check-create"
  | "check-upload-load"
  | "check-upload-submit"
  | "check-review-extract"
  | "share-load";

export type GraphNode =
  | "landing"
  | "dashboard"
  | "account-orders"
  | "account-order-detail"
  | "account-order-agreement"
  | "services"
  | "service-detail"
  | "service-questionnaire"
  | "connect"
  | "find-lawyer"
  | "find-lawyer-status"
  | "find-lawyer-paid"
  | "form8843"
  | "form8843-success"
  | "check"
  | "check-intake"
  | "check-upload"
  | "check-review"
  | "case"
  | "attorney"
  | "share"
  | "static";

export type GraphMockProfile =
  | "dashboard-recommended"
  | "dashboard-active-order"
  | "account-orders"
  | "services"
  | "service-detail"
  | "connect"
  | "service-questionnaire"
  | "form8843"
  | "order-detail"
  | "check"
  | "professional-search"
  | "professional-search-cpa"
  | "professional-search-unpaid"
  | "professional-search-running"
  | "professional-search-failed"
  | "professional-search-paid-unclaimed"
  | "professional-search-paid-claimed"
  | "case"
  | "case-empty-searches"
  | "case-engagements"
  | "case-documents-unassigned"
  | "case-gmail-connected"
  | "dashboard-upload-review"
  | "dashboard-empty-docs"
  | "attorney"
  | "attorney-approved"
  | "share"
  | "new-user"
  | "new-user-signup";

export interface GraphStep {
  selector: string;
  action?: "click" | "fill" | "select" | "setInputFiles" | "scrollToBottom" | "waitForSelector";
  value?: string;
  files?: string[];
}

export interface GraphEdge {
  id: string;
  node: GraphNode;
  route: string;
  selector: string;
  risk: GraphEdgeRisk;
  mockProfile?: GraphMockProfile;
  mockFailure?: GraphFailureKey;
  action?: "click" | "none";
  dialogAction?: "accept" | "dismiss";
  force?: boolean;
  before?: GraphStep[];
  defaultRun?: boolean;
  viewport?: {
    width: number;
    height: number;
  };
  expect?: {
    testId?: string;
    hiddenTestId?: string;
    selector?: string;
    text?: string | RegExp;
    urlPath?: string;
    hrefPath?: string;
    popupUrlPath?: string;
    download?: boolean;
    pressed?: boolean;
    failedResponsePath?: string;
  };
}

export const graphEdges: GraphEdge[] = [
  {
    id: "dashboard.switch-view.timeline",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-view-timeline']",
    risk: "safe",
    expect: { testId: "dashboard-timeline-view", pressed: true },
  },
  {
    id: "dashboard.switch-view.documents",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-view-documents']",
    risk: "safe",
    expect: { testId: "dashboard-documents-view", pressed: true },
  },
  {
    id: "dashboard.switch-view.deadlines",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-view-deadlines']",
    risk: "safe",
    expect: { testId: "dashboard-deadlines-view", pressed: true },
  },
  {
    id: "dashboard.switch-view.profile",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-view-profile']",
    risk: "safe",
    expect: { testId: "dashboard-profile-view", pressed: true },
  },
  {
    id: "dashboard.mobile.switch-view.documents",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-mobile-view-documents']",
    risk: "safe",
    viewport: { width: 390, height: 844 },
    expect: { testId: "dashboard-documents-view", pressed: true },
  },
  {
    id: "dashboard.mobile.service-center.active-order.fbar",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-service-order-fbar_check-mobile']",
    risk: "safe",
    mockProfile: "dashboard-active-order",
    viewport: { width: 390, height: 844 },
    expect: { urlPath: "/account/orders/order-fbar-active" },
  },
  {
    id: "dashboard.filter.category.tax",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-filter-category-tax']",
    risk: "safe",
    expect: { testId: "dashboard-active-filter", text: /Tax/i, pressed: true },
  },
  {
    id: "dashboard.filter.risk.needs_attention",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-filter-risk-needs-attention']",
    risk: "safe",
    expect: { testId: "dashboard-active-filter", text: /Needs attention/i, pressed: true },
  },
  {
    id: "dashboard.filter.risk.potential_risks",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-filter-risk-potential-risks']",
    risk: "safe",
    expect: { testId: "dashboard-active-filter", text: /Potential risks/i, pressed: true },
  },
  {
    id: "dashboard.clear-filter.main",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-clear-filter-main']",
    risk: "safe",
    before: [{ selector: "[data-testid='dashboard-filter-category-tax']" }],
    expect: { hiddenTestId: "dashboard-active-filter" },
  },
  {
    id: "dashboard.clear-filter.sidebar",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-clear-filter-sidebar']",
    risk: "safe",
    before: [{ selector: "[data-testid='dashboard-filter-category-tax']" }],
    expect: { hiddenTestId: "dashboard-active-filter" },
  },
  {
    id: "dashboard.empty-upload.open",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-empty-upload-cta-button']",
    risk: "safe",
    mockProfile: "dashboard-empty-docs",
    expect: { testId: "dashboard-upload-panel", text: /Upload documents/i },
  },
  {
    id: "dashboard.upload.open",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-open-upload-panel']",
    risk: "safe",
    expect: { testId: "dashboard-upload-panel", text: /Upload documents/i },
  },
  {
    id: "dashboard.upload.close",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-upload-panel-close']",
    risk: "safe",
    before: [{ selector: "[data-testid='dashboard-open-upload-panel']" }],
    expect: { hiddenTestId: "dashboard-upload-panel" },
  },
  {
    id: "dashboard.upload.submit-file",
    node: "dashboard",
    route: "/dashboard",
    selector: "body",
    action: "none",
    risk: "mutating",
    before: [
      { selector: "[data-testid='dashboard-open-upload-panel']" },
      { selector: "[data-testid='dashboard-upload-file-input']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
    ],
    expect: { text: /Dashboard updated|Tax return uploaded/i },
  },
  {
    id: "dashboard.upload.documents-view-open",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-upload-documents-view']",
    risk: "safe",
    before: [{ selector: "[data-testid='dashboard-view-documents']" }],
    expect: { testId: "dashboard-upload-panel", text: /Upload documents/i },
  },
  {
    id: "dashboard.upload.review-submit-selected",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-upload-selected']",
    risk: "mutating",
    mockProfile: "dashboard-upload-review",
    before: [
      { selector: "[data-testid='dashboard-open-upload-panel']" },
      { selector: "[data-testid='dashboard-upload-file-input']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
      { selector: "[data-testid='dashboard-upload-review']", action: "waitForSelector" },
      { selector: "[data-testid='dashboard-upload-review-toggle-0']" },
    ],
    expect: { text: /Dashboard updated|processed/i },
  },
  {
    id: "dashboard.openclaw.open",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-openclaw-toggle']",
    risk: "safe",
    expect: { testId: "dashboard-openclaw-popover", text: /OpenClaw/i },
  },
  {
    id: "dashboard.document-open.timeline-error",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-document-chip-doc-tax-return']",
    risk: "safe",
    mockFailure: "dashboard-document-open",
    expect: { testId: "dashboard-document-open-error", text: /Graph forced document open failure/i, failedResponsePath: "/api/dashboard/documents/doc-tax-return/view" },
  },
  {
    id: "dashboard.document-open.documents-error",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-document-view-doc-tax-return']",
    risk: "safe",
    mockFailure: "dashboard-document-open",
    before: [{ selector: "[data-testid='dashboard-view-documents']" }],
    expect: { testId: "dashboard-document-open-error", text: /Graph forced document open failure/i, failedResponsePath: "/api/dashboard/documents/doc-tax-return/view" },
  },
  {
    id: "dashboard.chat.send",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-chat-submit']",
    risk: "mutating",
    before: [
      { selector: "[data-testid='dashboard-chat-toggle']" },
      { selector: "[data-testid='dashboard-chat-input']", action: "fill", value: "What should I do next?" },
    ],
    expect: { testId: "dashboard-chat-messages", text: /Graph assistant reply/i },
  },
  {
    id: "dashboard.form-fill.extract",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='form-filler-submit']",
    risk: "mutating",
    before: [
      { selector: "[data-testid='dashboard-chat-toggle']" },
      { selector: "[data-testid='chat-mode-form-filler']" },
      { selector: "[data-testid='form-filler-file-input']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
      { selector: "[data-testid='form-filler-instruction']", action: "fill", value: "Fill with graph data" },
    ],
    expect: { testId: "form-preview-card", text: /Form Preview/i },
  },
  {
    id: "dashboard.form-fill.generate",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='form-preview-generate']",
    risk: "mutating",
    before: [
      { selector: "[data-testid='dashboard-chat-toggle']" },
      { selector: "[data-testid='chat-mode-form-filler']" },
      { selector: "[data-testid='form-filler-file-input']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
      { selector: "[data-testid='form-filler-submit']" },
      { selector: "[data-testid='form-preview-card']", action: "waitForSelector" },
    ],
    expect: { download: true },
  },
  {
    id: "dashboard.form-fill.invalid-file",
    node: "dashboard",
    route: "/dashboard",
    selector: "body",
    action: "none",
    risk: "safe",
    before: [
      { selector: "[data-testid='dashboard-chat-toggle']" },
      { selector: "[data-testid='chat-mode-form-filler']" },
      { selector: "[data-testid='form-filler-file-input']", action: "setInputFiles", files: ["tests/fixtures/synthetic/synthetic-brief.txt"] },
    ],
    expect: { testId: "form-filler-error", text: /Please upload a PDF file/i },
  },
  {
    id: "dashboard.service-center.recommended.fbar",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-recommended-service-fbar_check']",
    risk: "safe",
    mockProfile: "dashboard-recommended",
    expect: { urlPath: "/services/fbar_check" },
  },
  {
    id: "dashboard.service-center.active-order.fbar",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-service-order-fbar_check']",
    risk: "safe",
    mockProfile: "dashboard-active-order",
    expect: { urlPath: "/account/orders/order-fbar-active" },
  },
  {
    id: "dashboard.service-center.open-orders",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-open-orders']",
    risk: "safe",
    mockProfile: "dashboard-active-order",
    expect: { urlPath: "/account/orders" },
  },
  {
    id: "dashboard.service-center.browse-services",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-browse-services']",
    risk: "safe",
    mockProfile: "dashboard-active-order",
    expect: { urlPath: "/services" },
  },
  {
    id: "account-orders.browse-services",
    node: "account-orders",
    route: "/account/orders",
    selector: "[data-testid='account-orders-browse-services']",
    risk: "safe",
    expect: { urlPath: "/services" },
  },
  {
    id: "account-orders.back-dashboard",
    node: "account-orders",
    route: "/account/orders",
    selector: "[data-testid='account-orders-back-dashboard']",
    risk: "safe",
    expect: { urlPath: "/dashboard" },
  },
  {
    id: "account-orders.primary.83b",
    node: "account-orders",
    route: "/account/orders",
    selector: "[data-testid='account-order-primary-order-83b']",
    risk: "safe",
    expect: { urlPath: "/account/orders/order-83b" },
  },
  {
    id: "account-orders.service-link.83b",
    node: "account-orders",
    route: "/account/orders",
    selector: "[data-testid='account-order-service-order-83b']",
    risk: "safe",
    expect: { urlPath: "/services/election_83b" },
  },
  {
    id: "services.catalog.form8843",
    node: "services",
    route: "/services",
    selector: "[data-testid='services-product-form_8843_free']",
    risk: "safe",
    expect: { urlPath: "/form-8843" },
  },
  {
    id: "services.catalog.fbar",
    node: "services",
    route: "/services",
    selector: "[data-testid='services-product-fbar_check']",
    risk: "safe",
    expect: { urlPath: "/services/fbar_check" },
  },
  {
    id: "services.catalog.student-tax",
    node: "services",
    route: "/services",
    selector: "[data-testid='services-product-student_tax_1040nr']",
    risk: "safe",
    expect: { urlPath: "/services/student_tax_1040nr" },
  },
  {
    id: "services.catalog.h1b",
    node: "services",
    route: "/services",
    selector: "[data-testid='services-product-h1b_doc_check']",
    risk: "safe",
    expect: { urlPath: "/services/h1b_doc_check" },
  },
  {
    id: "services.catalog.83b",
    node: "services",
    route: "/services",
    selector: "[data-testid='services-product-election_83b']",
    risk: "safe",
    expect: { urlPath: "/services/election_83b" },
  },
  {
    id: "services.catalog.opt-execution",
    node: "services",
    route: "/services",
    selector: "[data-testid='services-product-opt_execution']",
    risk: "safe",
    expect: { urlPath: "/services/opt_execution" },
  },
  {
    id: "service-detail.opt-execution.start-questionnaire",
    node: "service-detail",
    route: "/services/opt_execution",
    selector: "[data-testid='service-start-opt_execution']",
    risk: "safe",
    expect: { urlPath: "/services/opt_execution/questionnaire" },
  },
  {
    id: "service-detail.fbar.start-order",
    node: "service-detail",
    route: "/services/fbar_check",
    selector: "[data-testid='service-start-fbar_check']",
    risk: "mutating",
    expect: { urlPath: "/account/orders/order-created" },
  },
  {
    id: "service-questionnaire.evaluate",
    node: "service-questionnaire",
    route: "/services/opt_execution/questionnaire",
    selector: "[data-testid='service-questionnaire-evaluate']",
    risk: "mutating",
    expect: { text: /Recommended plan/i },
  },
  {
    id: "service-questionnaire.rerun",
    node: "service-questionnaire",
    route: "/services/opt_execution/questionnaire",
    selector: "[data-testid='service-questionnaire-rerun']",
    risk: "mutating",
    before: [{ selector: "[data-testid='service-questionnaire-evaluate']" }],
    expect: { selector: "[data-testid='service-questionnaire-evaluate']", text: /See recommendation/i },
  },
  {
    id: "service-questionnaire.execution-continue",
    node: "service-questionnaire",
    route: "/services/opt_execution/questionnaire",
    selector: "[data-testid='service-questionnaire-continue']",
    risk: "mutating",
    before: [
      { selector: "[data-testid='service-questionnaire-evaluate']" },
      { selector: "[data-testid='service-questionnaire-mode-execution']" },
    ],
    expect: { urlPath: "/account/orders/order-created" },
  },
  {
    id: "service-questionnaire.advisory-continue",
    node: "service-questionnaire",
    route: "/services/opt_execution/questionnaire",
    selector: "[data-testid='service-questionnaire-continue']",
    risk: "mutating",
    before: [
      { selector: "[data-testid='service-questionnaire-evaluate']" },
      { selector: "[data-testid='service-questionnaire-mode-advisory']" },
    ],
    expect: { urlPath: "/account/orders/order-created" },
  },
  {
    id: "connect.select-codex",
    node: "connect",
    route: "/connect",
    selector: "[data-testid='connect-app-codex']",
    risk: "safe",
    mockProfile: "connect",
    expect: { text: /~\/\.codex\/config\.toml/i },
  },
  {
    id: "connect.generate-token",
    node: "connect",
    route: "/connect",
    selector: "[data-testid='connect-token-button']",
    risk: "mutating",
    mockProfile: "connect",
    before: [{ selector: "[data-testid='connect-app-codex']" }],
    expect: { testId: "connect-copy-token", text: /Copy token/i },
  },
  {
    id: "connect.copy-token",
    node: "connect",
    route: "/connect",
    selector: "[data-testid='connect-copy-token']",
    risk: "safe",
    mockProfile: "connect",
    before: [
      { selector: "[data-testid='connect-app-codex']" },
      { selector: "[data-testid='connect-token-button']" },
    ],
    expect: { testId: "connect-copy-token", text: /Copied/i },
  },
  {
    id: "connect.copy-config",
    node: "connect",
    route: "/connect",
    selector: "[data-testid='connect-copy-config']",
    risk: "safe",
    mockProfile: "connect",
    before: [
      { selector: "[data-testid='connect-app-codex']" },
      { selector: "[data-testid='connect-token-button']" },
    ],
    expect: { testId: "connect-copy-config", text: /Copied/i },
  },
  {
    id: "find-lawyer.sample-report",
    node: "find-lawyer",
    route: "/find-lawyer",
    selector: "[data-testid='find-lawyer-sample-report']",
    risk: "safe",
    expect: { popupUrlPath: "/samples/lawyer-search-eb5-sample.pdf" },
  },
  {
    id: "find-lawyer.submit-search",
    node: "find-lawyer",
    route: "/find-lawyer",
    selector: "[data-testid='find-lawyer-submit']",
    risk: "mutating",
    mockProfile: "professional-search",
    before: [
      { selector: "[data-testid='find-lawyer-purpose']", action: "fill", value: "H-1B attorney shortlist" },
      { selector: "[data-testid='find-lawyer-brief']", action: "fill", value: "I need an immigration attorney for an H-1B transfer with prior F-1 OPT history, a pending employer timeline, wage-level questions, and a need to compare boutique and startup-focused firms. The case includes travel timing, document review, and communication with a fast-moving employer. I want verified firms with clear federal immigration experience and transparent fee ranges." },
      { selector: "[data-testid='find-lawyer-files']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
    ],
    expect: { urlPath: "/find-lawyer/search-complete" },
  },
  {
    id: "find-lawyer.vertical-switch",
    node: "find-lawyer",
    route: "/find-lawyer",
    selector: "body",
    action: "none",
    risk: "safe",
    before: [{ selector: "[data-testid='find-lawyer-vertical']", action: "select", value: "cpa" }],
    expect: { text: /CPA|tax/i },
  },
  {
    id: "find-lawyer.submit-cpa-search",
    node: "find-lawyer",
    route: "/find-lawyer",
    selector: "[data-testid='find-lawyer-submit']",
    risk: "mutating",
    mockProfile: "professional-search-cpa",
    before: [
      { selector: "[data-testid='find-lawyer-vertical']", action: "select", value: "cpa" },
      { selector: "[data-testid='find-lawyer-purpose']", action: "fill", value: "Nonresident CPA and Form 5472 support" },
      { selector: "[data-testid='find-lawyer-brief']", action: "fill", value: "I need a CPA search for a nonresident founder with a single-member US LLC, possible Form 5472 and pro forma 1120 filing requirements, prior F-1 student tax filings, FBAR questions, and a need to compare international tax CPAs who understand disregarded entities, NRA owner reporting, bookkeeping cleanup, and fixed-fee compliance engagements." },
      { selector: "[data-testid='find-lawyer-files']", action: "setInputFiles", files: ["tests/fixtures/synthetic/synthetic-tax-return.pdf"] },
    ],
    expect: { urlPath: "/find-lawyer/search-cpa", text: /Graph International CPA|nonresident tax/i },
  },
  {
    id: "find-lawyer.status.marketplace-match",
    node: "find-lawyer-status",
    route: "/find-lawyer/search-paid",
    selector: "[data-testid='find-lawyer-marketplace-opt_execution']",
    risk: "safe",
    mockProfile: "professional-search",
    expect: { urlPath: "/services/opt_execution" },
  },
  {
    id: "find-lawyer.status.open-case",
    node: "find-lawyer-status",
    route: "/find-lawyer/search-paid",
    selector: "[data-testid='find-lawyer-open-case']",
    risk: "safe",
    mockProfile: "professional-search",
    expect: { urlPath: "/case/case-graph" },
  },
  {
    id: "find-lawyer.status.track-one",
    node: "find-lawyer-status",
    route: "/find-lawyer/search-paid",
    selector: "[data-testid='find-lawyer-track-graph-immigration-llp']",
    risk: "mutating",
    mockProfile: "professional-search",
    expect: { text: /tracking/i },
  },
  {
    id: "find-lawyer.status.unpaid-checkout-error",
    node: "find-lawyer-status",
    route: "/find-lawyer/search-complete",
    selector: "[data-testid='find-lawyer-checkout']",
    risk: "safe",
    mockProfile: "professional-search-unpaid",
    mockFailure: "professional-search-checkout",
    expect: { testId: "find-lawyer-checkout-error", text: /Graph forced professional search checkout failure/i, failedResponsePath: "/api/professional-search/search-complete/checkout" },
  },
  {
    id: "find-lawyer.status.running",
    node: "find-lawyer-status",
    route: "/find-lawyer/search-running",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "professional-search-running",
    expect: { text: /Searching|running|queued/i },
  },
  {
    id: "find-lawyer.status.failed",
    node: "find-lawyer-status",
    route: "/find-lawyer/search-failed",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "professional-search-failed",
    expect: { text: /Graph search failed/i },
  },
  {
    id: "find-lawyer.status.track-top-3",
    node: "find-lawyer-status",
    route: "/find-lawyer/search-complete",
    selector: "[data-testid='find-lawyer-track-top-3']",
    risk: "mutating",
    mockProfile: "professional-search",
    expect: { text: /tracked for this case/i },
  },
  {
    id: "find-lawyer.status.download-pdf",
    node: "find-lawyer-status",
    route: "/find-lawyer/search-paid",
    selector: "[data-testid='find-lawyer-report-download-pdf']",
    risk: "safe",
    mockProfile: "professional-search",
    expect: { download: true },
  },
  {
    id: "find-lawyer.paid.download-pdf",
    node: "find-lawyer-paid",
    route: "/find-lawyer/search-paid/paid?session_id=cs_graph",
    selector: "[data-testid='find-lawyer-paid-download-pdf']",
    action: "none",
    risk: "safe",
    mockProfile: "professional-search",
    expect: { hrefPath: "/api/professional-search/search-paid/download", text: /Your report is unlocked/i },
  },
  {
    id: "find-lawyer.paid.claim-signup",
    node: "find-lawyer-paid",
    route: "/find-lawyer/search-paid/paid?session_id=cs_graph",
    selector: "[data-testid='find-lawyer-paid-auth-submit']",
    risk: "mutating",
    mockProfile: "professional-search-paid-unclaimed",
    before: [
      { selector: "[data-testid='find-lawyer-paid-email']", action: "fill", value: "graph@example.com" },
      { selector: "[data-testid='find-lawyer-paid-password']", action: "fill", value: "password123" },
    ],
    expect: { urlPath: "/case/case-graph" },
  },
  {
    id: "find-lawyer.paid.claim-login-error",
    node: "find-lawyer-paid",
    route: "/find-lawyer/search-paid/paid?session_id=cs_graph",
    selector: "[data-testid='find-lawyer-paid-auth-submit']",
    risk: "mutating",
    mockProfile: "professional-search-paid-unclaimed",
    mockFailure: "professional-search-claim",
    before: [
      { selector: "[data-testid='find-lawyer-paid-auth-toggle']" },
      { selector: "[data-testid='find-lawyer-paid-email']", action: "fill", value: "graph@example.com" },
      { selector: "[data-testid='find-lawyer-paid-password']", action: "fill", value: "password123" },
    ],
    expect: { testId: "find-lawyer-paid-auth-error", text: /Graph forced professional search claim failure/i, failedResponsePath: "/api/professional-search/search-paid/claim" },
  },
  {
    id: "find-lawyer.paid.start-pro-trial",
    node: "find-lawyer-paid",
    route: "/find-lawyer/search-paid/paid?session_id=cs_graph",
    selector: "[data-testid='find-lawyer-paid-start-trial']",
    risk: "mutating",
    mockProfile: "professional-search-paid-claimed",
    expect: { testId: "find-lawyer-paid-trial-started", text: /Pro trial/i },
  },
  {
    id: "find-lawyer.paid.start-pro-trial-error",
    node: "find-lawyer-paid",
    route: "/find-lawyer/search-paid/paid?session_id=cs_graph",
    selector: "[data-testid='find-lawyer-paid-start-trial']",
    risk: "mutating",
    mockProfile: "professional-search-paid-claimed",
    mockFailure: "professional-search-trial",
    expect: { testId: "find-lawyer-paid-trial-error", text: /Graph forced professional search trial failure/i, failedResponsePath: "/api/professional-search/search-paid/start-pro-trial" },
  },
  {
    id: "find-lawyer.paid.view-web",
    node: "find-lawyer-paid",
    route: "/find-lawyer/search-paid/paid?session_id=cs_graph",
    selector: "[data-testid='find-lawyer-paid-view-web']",
    risk: "safe",
    mockProfile: "professional-search",
    expect: { popupUrlPath: "/api/professional-search/search-paid/download" },
  },
  {
    id: "case.new.redirect-discovery",
    node: "case",
    route: "/case/new",
    selector: "body",
    action: "none",
    risk: "mutating",
    mockProfile: "case",
    expect: { urlPath: "/case/case-graph/discovery" },
  },
  {
    id: "case.discovery.smoke",
    node: "case",
    route: "/case/case-graph/discovery",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "case",
    expect: { text: /Concerns|Continue/i },
  },
  {
    id: "case.discovery.next-back",
    node: "case",
    route: "/case/case-graph/discovery",
    selector: "[data-testid='case-discovery-back']",
    risk: "mutating",
    mockProfile: "case",
    before: [{ selector: "[data-testid='case-discovery-next']" }],
    expect: { text: /What brings you here today/i },
  },
  {
    id: "case.documents.smoke",
    node: "case",
    route: "/case/case-graph/documents",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "case",
    expect: { text: /Document Data Room|required documents/i },
  },
  {
    id: "case.documents.upload-general",
    node: "case",
    route: "/case/case-graph/documents",
    selector: "body",
    action: "none",
    risk: "mutating",
    mockProfile: "case-documents-unassigned",
    before: [{ selector: "[data-testid='case-doc-general-upload-input']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] }],
    expect: { testId: "case-doc-row-case-doc-uploaded", text: /graph-document\.pdf/i },
  },
  {
    id: "case.documents.assign-slot",
    node: "case",
    route: "/case/case-graph/documents",
    selector: "body",
    action: "none",
    risk: "mutating",
    mockProfile: "case-documents-unassigned",
    before: [{ selector: "[data-testid='case-doc-assign-case-doc-unassigned']", action: "select", value: "i94" }],
    expect: { testId: "case-doc-slot-i94", text: /unassigned\.pdf/i },
  },
  {
    id: "case.documents.remove-slot",
    node: "case",
    route: "/case/case-graph/documents",
    selector: "[data-testid='case-doc-slot-remove-passport']",
    risk: "mutating",
    mockProfile: "case",
    expect: { text: /1 required documents remaining|Passport/i },
  },
  {
    id: "case.overview.back-dashboard",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-overview-back-dashboard']",
    risk: "safe",
    mockProfile: "case",
    expect: { urlPath: "/dashboard" },
  },
  {
    id: "case.overview.find-specialist-empty",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-lawyers-find-specialist']",
    risk: "safe",
    mockProfile: "case-empty-searches",
    expect: { urlPath: "/find-lawyer" },
  },
  {
    id: "case.overview.launch-lawyer",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-lawyers-new-search']",
    risk: "safe",
    mockProfile: "case",
    expect: { urlPath: "/find-lawyer" },
  },
  {
    id: "case.engagement.add-firm",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-engagement-add-submit']",
    risk: "mutating",
    mockProfile: "case",
    before: [
      { selector: "[data-testid='case-engagement-add-open']" },
      { selector: "[data-testid='case-engagement-new-name']", action: "fill", value: "Graph Added Firm" },
    ],
    expect: { text: /Graph Added Firm/i },
  },
  {
    id: "case.lawyers.track-one",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-lawyers-track-graph-immigration-llp']",
    risk: "mutating",
    mockProfile: "case",
    expect: { text: /tracking|Graph Immigration LLP/i },
  },
  {
    id: "case.engagement.status-update",
    node: "case",
    route: "/case/case-graph",
    selector: "body",
    action: "none",
    risk: "mutating",
    mockProfile: "case-engagements",
    before: [{ selector: "[data-testid='case-engagement-status-engagement-graph']", action: "select", value: "in_discussion" }],
    expect: { text: /in discussion/i },
  },
  {
    id: "case.engagement.notes-save",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-engagement-notes-save-engagement-graph']",
    risk: "mutating",
    mockProfile: "case-engagements",
    before: [
      { selector: "[data-testid='case-engagement-notes-open-engagement-graph']" },
      { selector: "[data-testid='case-engagement-notes-input-engagement-graph']", action: "fill", value: "Graph updated notes" },
    ],
    expect: { text: /Graph updated notes/i },
  },
  {
    id: "case.engagement.email-draft",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-engagement-email-engagement-graph']",
    risk: "safe",
    mockProfile: "case-engagements",
    expect: { text: /outreach sent/i },
  },
  {
    id: "case.engagement.delete-cancel",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-engagement-delete-engagement-graph']",
    risk: "safe",
    mockProfile: "case-engagements",
    dialogAction: "dismiss",
    expect: { text: /Graph Immigration LLP/i },
  },
  {
    id: "case.engagement.delete-confirm",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-engagement-delete-engagement-graph']",
    risk: "mutating",
    mockProfile: "case-engagements",
    dialogAction: "accept",
    expect: { text: /No firms tracked yet/i },
  },
  {
    id: "case.gmail.disconnect-cancel",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-gmail-disconnect']",
    risk: "safe",
    mockProfile: "case-gmail-connected",
    dialogAction: "dismiss",
    expect: { text: /connected/i },
  },
  {
    id: "case.gmail.disconnect-confirm",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-gmail-disconnect']",
    risk: "mutating",
    mockProfile: "case-gmail-connected",
    dialogAction: "accept",
    expect: { text: /not connected/i },
  },
  {
    id: "attorney.dashboard.open-case",
    node: "attorney",
    route: "/attorney/dashboard",
    selector: "[data-testid='attorney-open-case-order-opt-intake-complete']",
    risk: "safe",
    mockProfile: "attorney",
    expect: { urlPath: "/attorney/cases/order-opt-intake-complete" },
  },
  {
    id: "attorney.case.approve-review",
    node: "attorney",
    route: "/attorney/cases/order-opt-intake-complete",
    selector: "[data-testid='attorney-case-approve-review']",
    risk: "mutating",
    mockProfile: "attorney",
    before: [
      { selector: "[data-testid='attorney-checklist-identity']" },
      { selector: "[data-testid='attorney-checklist-eligibility']" },
      { selector: "[data-testid='attorney-case-notes']", action: "fill", value: "Graph review notes" },
    ],
    expect: { text: /ready for filing|Review recorded/i },
  },
  {
    id: "attorney.case.flag-upgrade",
    node: "attorney",
    route: "/attorney/cases/order-opt-intake-complete",
    selector: "[data-testid='attorney-case-flag-upgrade']",
    risk: "mutating",
    mockProfile: "attorney",
    before: [
      { selector: "[data-testid='attorney-checklist-identity']" },
      { selector: "[data-testid='attorney-case-notes']", action: "fill", value: "Needs strategy review" },
    ],
    expect: { text: /flagged for upgrade|Case flagged/i },
  },
  {
    id: "attorney.case.record-filing",
    node: "attorney",
    route: "/attorney/cases/order-opt-intake-complete",
    selector: "[data-testid='attorney-case-record-filing']",
    risk: "mutating",
    mockProfile: "attorney-approved",
    before: [
      { selector: "[data-testid='attorney-case-receipt-number']", action: "fill", value: "IOE1234567890" },
      { selector: "[data-testid='attorney-case-filing-confirmation']", action: "fill", value: "Filed through graph test" },
    ],
    expect: { text: /Filing recorded with receipt IOE1234567890/i },
  },
  {
    id: "order-detail.pull-prefill.83b",
    node: "account-order-detail",
    route: "/account/orders/order-83b-draft",
    selector: "[data-testid='order-detail-pull-prefill']",
    risk: "mutating",
    mockProfile: "order-detail",
    expect: { text: /mocked prefill applied/i },
  },
  {
    id: "order-detail.save-intake.83b",
    node: "account-order-detail",
    route: "/account/orders/order-83b-draft",
    selector: "[data-testid='order-detail-save-intake']",
    risk: "mutating",
    mockProfile: "order-detail",
    before: [
      { selector: "[data-testid='order-83b-taxpayer-name']", action: "fill", value: "Jessica Chen" },
      { selector: "[data-testid='order-83b-taxpayer-address']", action: "fill", value: "123 Startup Way, San Francisco, CA" },
      { selector: "[data-testid='order-83b-company-name']", action: "fill", value: "GraphCo, Inc." },
      { selector: "[data-testid='order-83b-grant-date']", action: "fill", value: "2026-04-01" },
      { selector: "[data-testid='order-83b-property-description']", action: "fill", value: "Restricted common stock" },
      { selector: "[data-testid='order-83b-share-count']", action: "fill", value: "10000" },
      { selector: "[data-testid='order-83b-fmv']", action: "fill", value: "0.02" },
      { selector: "[data-testid='order-83b-exercise-price']", action: "fill", value: "0.01" },
      { selector: "[data-testid='order-83b-vesting-schedule']", action: "fill", value: "25% after 12 months, monthly thereafter" },
    ],
    expect: { text: /83\(b\) intake saved/i },
  },
  {
    id: "order-detail.run-now.83b",
    node: "account-order-detail",
    route: "/account/orders/order-83b-ready",
    selector: "[data-testid='order-detail-run-now']",
    risk: "mutating",
    mockProfile: "order-detail",
    expect: { text: /Processing complete/i },
  },
  {
    id: "order-detail.mark-mailed.83b",
    node: "account-order-detail",
    route: "/account/orders/order-83b-result",
    selector: "[data-testid='order-detail-mark-mailed']",
    risk: "mutating",
    mockProfile: "order-detail",
    before: [{ selector: "[data-testid='order-detail-tracking-number']", action: "fill", value: "9407100000000000123456" }],
    expect: { text: /Mailing confirmation saved/i },
  },
  {
    id: "order-detail.download-artifact.83b",
    node: "account-order-detail",
    route: "/account/orders/order-83b-result",
    selector: "[data-testid='order-detail-artifact-83b-election-pdf']",
    risk: "safe",
    mockProfile: "order-detail",
    expect: { download: true },
  },
  {
    id: "order-detail.reopen-service.83b",
    node: "account-order-detail",
    route: "/account/orders/order-83b-result",
    selector: "[data-testid='order-detail-reopen-service']",
    risk: "safe",
    mockProfile: "order-detail",
    expect: { urlPath: "/services/election_83b" },
  },
  {
    id: "order-detail.pull-prefill.opt",
    node: "account-order-detail",
    route: "/account/orders/order-opt-draft",
    selector: "[data-testid='order-detail-opt-pull-prefill']",
    risk: "mutating",
    mockProfile: "order-detail",
    expect: { text: /mocked prefill applied/i },
  },
  {
    id: "order-detail.save-intake.opt",
    node: "account-order-detail",
    route: "/account/orders/order-opt-draft",
    selector: "[data-testid='order-detail-opt-save-intake']",
    risk: "mutating",
    mockProfile: "order-detail",
    before: [
      { selector: "[data-testid='order-opt-start-date']", action: "fill", value: "2026-05-15" },
      { selector: "[data-testid='order-opt-employment-plan']", action: "fill", value: "Software engineering role related to degree program." },
    ],
    expect: { text: /OPT intake saved/i },
  },
  {
    id: "order-detail.open-agreement.opt",
    node: "account-order-detail",
    route: "/account/orders/order-opt-intake-complete",
    selector: "[data-testid='order-detail-open-agreement']",
    risk: "safe",
    mockProfile: "order-detail",
    expect: { urlPath: "/account/orders/order-opt-intake-complete/agreement" },
  },
  {
    id: "order-agreement.sign.opt",
    node: "account-order-agreement",
    route: "/account/orders/order-opt-intake-complete/agreement",
    selector: "[data-testid='order-agreement-sign']",
    risk: "mutating",
    mockProfile: "order-detail",
    before: [
      { selector: "[data-testid='order-agreement-text']", action: "scrollToBottom" },
      { selector: "[data-testid='order-agreement-signature']", action: "fill", value: "Jessica Chen" },
    ],
    expect: { urlPath: "/account/orders/order-opt-intake-complete" },
  },
  {
    id: "form8843.generate",
    node: "form8843",
    route: "/form-8843",
    selector: "[data-testid='form8843-wizard-generate']",
    risk: "mutating",
    mockProfile: "form8843",
    before: [
      { selector: "[data-testid='form8843-field-full_name']", action: "fill", value: "Jessica Chen" },
      { selector: "[data-testid='form8843-wizard-continue']" },
      { selector: "[data-testid='form8843-field-arrival_date']", action: "fill", value: "2024-08-20" },
      { selector: "[data-testid='form8843-wizard-continue']" },
      { selector: "[data-testid='form8843-field-school_name']", action: "fill", value: "Columbia University" },
      { selector: "[data-testid='form8843-wizard-continue']" },
      { selector: "[data-testid='form8843-field-citizenship_country']", action: "fill", value: "China" },
      { selector: "[data-testid='form8843-wizard-continue']" },
      { selector: "[data-testid='form8843-field-2025']", action: "fill", value: "120" },
      { selector: "[data-testid='form8843-field-2024']", action: "fill", value: "90" },
      { selector: "[data-testid='form8843-wizard-continue']" },
    ],
    expect: { urlPath: "/form-8843/success" },
  },
  {
    id: "form8843-success.download-pdf",
    node: "form8843-success",
    route: "/form-8843/success?orderId=form8843-order",
    selector: "[data-testid='form8843-success-download']",
    risk: "safe",
    mockProfile: "form8843",
    expect: { download: true },
  },
  {
    id: "form8843-success.copy-mailing-address",
    node: "form8843-success",
    route: "/form-8843/success?orderId=form8843-order",
    selector: "[data-testid='form8843-copy-mailing-address']",
    risk: "safe",
    mockProfile: "form8843",
    expect: { testId: "form8843-copy-mailing-address", text: /copied/i },
  },
  {
    id: "form8843-success.download-mailing-kit",
    node: "form8843-success",
    route: "/form-8843/success?orderId=form8843-order",
    selector: "[data-testid='form8843-download-mailing-kit']",
    risk: "safe",
    mockProfile: "form8843",
    expect: { download: true },
  },
  {
    id: "form8843-success.start-another",
    node: "form8843-success",
    route: "/form-8843/success?orderId=form8843-order",
    selector: "[data-testid='form8843-success-start-another']",
    risk: "safe",
    mockProfile: "form8843",
    expect: { urlPath: "/form-8843" },
  },
  {
    id: "form8843-success.mark-mailed",
    node: "form8843-success",
    route: "/form-8843/success?orderId=form8843-order",
    selector: "[data-testid='form8843-mark-mailed']",
    risk: "mutating",
    mockProfile: "form8843",
    before: [{ selector: "[data-testid='form8843-mailing-tracking']", action: "fill", value: "9407100000000000123456" }],
    expect: { text: /Marked as mailed|Guardian has stopped/i },
  },
  {
    id: "check.student.intake-continue",
    node: "check-intake",
    route: "/check/student",
    selector: "[data-testid='student-intake-continue']",
    risk: "mutating",
    mockProfile: "check",
    before: [
      { selector: "[data-testid='student-intake-student_status-enrolled_cpt']" },
      { selector: "[data-testid='student-intake-has_cpt_authorization-yes']" },
      { selector: "[data-testid='student-intake-cpt_fulltime_months-1-6']" },
      { selector: "[data-testid='student-intake-income_reporting-sprintax']" },
      { selector: "[data-testid='student-intake-planning_travel-no']" },
    ],
    expect: { urlPath: "/check/student/upload" },
  },
  {
    id: "check.select.student",
    node: "check",
    route: "/check",
    selector: "[data-testid='check-track-student']",
    risk: "safe",
    mockProfile: "new-user",
    expect: { urlPath: "/check/student" },
  },
  {
    id: "check.select.entity",
    node: "check",
    route: "/check",
    selector: "[data-testid='check-track-entity']",
    risk: "safe",
    mockProfile: "new-user",
    expect: { urlPath: "/check/entity" },
  },
  {
    id: "check.select.stem",
    node: "check",
    route: "/check",
    selector: "[data-testid='check-track-stem-opt']",
    risk: "safe",
    mockProfile: "new-user",
    expect: { urlPath: "/check/stem-opt" },
  },
  {
    id: "check.student.upload-continue",
    node: "check-upload",
    route: "/check/student/upload?id=student-check",
    selector: "[data-testid='student-upload-continue']",
    risk: "mutating",
    mockProfile: "check",
    before: [
      { selector: "[data-testid='student-upload-input-i20']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
      { selector: "text=Uploaded", action: "waitForSelector" },
    ],
    expect: { urlPath: "/check/student/review" },
  },
  {
    id: "check.student.review-snapshot",
    node: "check-review",
    route: "/check/student/review?id=student-check",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "check",
    expect: { text: /Your Student Check/i },
  },
  {
    id: "check.entity.intake-continue",
    node: "check-intake",
    route: "/check/entity",
    selector: "[data-testid='entity-intake-continue']",
    risk: "mutating",
    mockProfile: "check",
    before: [
      { selector: "[data-testid='entity-intake-entity_type-smllc']" },
      { selector: "[data-testid='entity-intake-owner_residency-on_visa']" },
      { selector: "[data-testid='entity-intake-visa_type-f1_opt_stem']" },
      { selector: "[data-testid='entity-intake-state-of-formation']", action: "fill", value: "Delaware" },
      { selector: "[data-testid='entity-intake-separate_bank_account-yes']" },
      { selector: "[data-testid='entity-intake-foreign_capital_transfer-no']" },
      { selector: "[data-testid='entity-intake-formation_age-this_year']" },
      { selector: "[data-testid='entity-intake-tax_software_used-sprintax']" },
    ],
    expect: { urlPath: "/check/entity/upload" },
  },
  {
    id: "check.entity.upload-continue",
    node: "check-upload",
    route: "/check/entity/upload?id=entity-check",
    selector: "[data-testid='entity-upload-continue']",
    risk: "mutating",
    mockProfile: "check",
    before: [
      { selector: "[data-testid='entity-upload-input-tax-return']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
      { selector: "text=Uploaded", action: "waitForSelector" },
    ],
    expect: { urlPath: "/check/entity/review" },
  },
  {
    id: "check.entity.review-snapshot",
    node: "check-review",
    route: "/check/entity/review?id=entity-check",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "check",
    expect: { text: /Your Entity Check/i },
  },
  {
    id: "check.stem.intake-continue",
    node: "check-intake",
    route: "/check/stem-opt",
    selector: "[data-testid='stem-intake-continue']",
    risk: "mutating",
    mockProfile: "check",
    before: [
      { selector: "[data-testid='stem-intake-stage-stem_opt']" },
      { selector: "[data-testid='stem-intake-years']", action: "fill", value: "3" },
      { selector: "[data-testid='stem-intake-employment_status-employed']" },
      { selector: "[data-testid='stem-intake-employer_changed-no']" },
      { selector: "[data-testid='stem-intake-tax_software_used-sprintax']" },
    ],
    expect: { urlPath: "/check/stem-opt/upload" },
  },
  {
    id: "check.stem.upload-continue",
    node: "check-upload",
    route: "/check/stem-opt/upload?id=stem-check",
    selector: "[data-testid='stem-upload-continue']",
    risk: "mutating",
    mockProfile: "check",
    before: [
      { selector: "[data-testid='stem-upload-input-employment_letter']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
      { selector: "[data-testid='stem-upload-input-i983']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
      { selector: "text=Uploaded", action: "waitForSelector" },
    ],
    expect: { urlPath: "/check/stem-opt/review" },
  },
  {
    id: "check.stem.review-snapshot",
    node: "check-review",
    route: "/check/stem-opt/review?id=stem-check",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "check",
    expect: { text: /Your STEM OPT Check/i },
  },
  {
    id: "static.home",
    node: "landing",
    route: "/",
    selector: "body",
    action: "none",
    risk: "safe",
    expect: { text: /Guardian/i },
  },
  {
    id: "static.pricing",
    node: "static",
    route: "/pricing",
    selector: "body",
    action: "none",
    risk: "safe",
    expect: { text: /Guardian Pro|Pricing/i },
  },
  {
    id: "static.docs-install",
    node: "static",
    route: "/docs/install",
    selector: "body",
    action: "none",
    risk: "safe",
    expect: { text: /Download guardian\.dxt|Get token/i },
  },
  {
    id: "static.privacy",
    node: "static",
    route: "/privacy",
    selector: "body",
    action: "none",
    risk: "safe",
    expect: { text: /Privacy/i },
  },
  {
    id: "static.login",
    node: "static",
    route: "/login",
    selector: "body",
    action: "none",
    risk: "safe",
    expect: { text: /Sign in|Continue/i },
  },
  {
    id: "auth.login.success",
    node: "static",
    route: "/login?next=/dashboard",
    selector: "[data-testid='login-submit']",
    risk: "mutating",
    before: [
      { selector: "[data-testid='login-email']", action: "fill", value: "test@123.com" },
      { selector: "[data-testid='login-password']", action: "fill", value: "test123" },
    ],
    expect: { urlPath: "/dashboard" },
  },
  {
    id: "auth.login.failure",
    node: "static",
    route: "/login",
    selector: "[data-testid='login-submit']",
    risk: "safe",
    mockFailure: "auth-login",
    before: [
      { selector: "[data-testid='login-email']", action: "fill", value: "bad@example.com" },
      { selector: "[data-testid='login-password']", action: "fill", value: "badpass" },
    ],
    expect: { testId: "login-error", text: /Graph forced auth failure/i, failedResponsePath: "/api/auth/login" },
  },
  {
    id: "auth.register.success",
    node: "static",
    route: "/login?next=/dashboard",
    selector: "[data-testid='login-submit']",
    risk: "mutating",
    mockProfile: "new-user-signup",
    before: [
      { selector: "[data-testid='login-toggle-register']" },
      { selector: "[data-testid='login-email']", action: "fill", value: "synthetic.signup@example.test" },
      { selector: "[data-testid='login-password']", action: "fill", value: "synthetic123" },
    ],
    expect: { urlPath: "/dashboard" },
  },
  {
    id: "auth.register.failure",
    node: "static",
    route: "/login",
    selector: "[data-testid='login-submit']",
    risk: "safe",
    mockFailure: "auth-register",
    mockProfile: "new-user-signup",
    before: [
      { selector: "[data-testid='login-toggle-register']" },
      { selector: "[data-testid='login-email']", action: "fill", value: "duplicate@example.test" },
      { selector: "[data-testid='login-password']", action: "fill", value: "synthetic123" },
    ],
    expect: { testId: "login-error", text: /Graph forced registration failure/i, failedResponsePath: "/api/auth/register" },
  },
  {
    id: "share.route-smoke",
    node: "share",
    route: "/share/share-token",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "share",
    expect: { text: /Download all|Shared/i },
  },
  {
    id: "share.download-all",
    node: "share",
    route: "/share/share-token",
    selector: "[data-testid='share-download-all']",
    risk: "safe",
    mockProfile: "share",
    expect: { download: true },
  },
  {
    id: "share.preview-open",
    node: "share",
    route: "/share/share-token",
    selector: "[data-testid='share-slot-passport']",
    risk: "safe",
    mockProfile: "share",
    expect: { testId: "share-preview-drawer", text: /Passport/i },
  },
  {
    id: "share.preview-close",
    node: "share",
    route: "/share/share-token",
    selector: "[data-testid='share-preview-close']",
    risk: "safe",
    mockProfile: "share",
    before: [{ selector: "[data-testid='share-slot-passport']" }],
    expect: { hiddenTestId: "share-preview-drawer" },
  },
  {
    id: "dashboard.voice.start",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-voice-toggle']",
    risk: "safe",
    expect: { text: /Mock voice review started/i },
  },
  {
    id: "dashboard.error.timeline",
    node: "dashboard",
    route: "/dashboard",
    selector: "body",
    action: "none",
    risk: "safe",
    mockFailure: "dashboard-timeline",
    expect: { text: /Graph forced dashboard timeline failure/i, failedResponsePath: "/api/dashboard/timeline" },
  },
  {
    id: "dashboard.error.stats",
    node: "dashboard",
    route: "/dashboard",
    selector: "body",
    action: "none",
    risk: "safe",
    mockFailure: "dashboard-stats",
    expect: { text: /Graph forced dashboard stats failure/i, failedResponsePath: "/api/dashboard/stats" },
  },
  {
    id: "dashboard.error.documents",
    node: "dashboard",
    route: "/dashboard",
    selector: "body",
    action: "none",
    risk: "safe",
    mockFailure: "dashboard-documents",
    expect: { text: /Graph forced dashboard documents failure/i, failedResponsePath: "/api/dashboard/documents" },
  },
  {
    id: "dashboard.error.load-retry",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-load-retry']",
    risk: "safe",
    mockFailure: "dashboard-timeline",
    expect: { text: /Graph forced dashboard timeline failure/i, failedResponsePath: "/api/dashboard/timeline" },
  },
  {
    id: "dashboard.error.openclaw-connection",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-openclaw-toggle']",
    risk: "safe",
    mockFailure: "dashboard-openclaw-connection",
    expect: { text: /Graph forced OpenClaw connection failure/i, failedResponsePath: "/api/auth/openclaw/connection" },
  },
  {
    id: "dashboard.error.openclaw-token",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-openclaw-token-button']",
    risk: "mutating",
    mockFailure: "dashboard-openclaw-token",
    before: [{ selector: "[data-testid='dashboard-openclaw-toggle']" }],
    expect: { text: /Graph forced OpenClaw token failure/i, failedResponsePath: "/api/auth/openclaw/token" },
  },
  {
    id: "dashboard.error.upload-prepare",
    node: "dashboard",
    route: "/dashboard",
    selector: "body",
    action: "none",
    risk: "mutating",
    mockFailure: "dashboard-upload-prepare",
    before: [
      { selector: "[data-testid='dashboard-open-upload-panel']" },
      { selector: "[data-testid='dashboard-upload-file-input']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
    ],
    expect: { text: /Graph forced dashboard upload prepare failure/i, failedResponsePath: "/api/dashboard/upload/prepare" },
  },
  {
    id: "dashboard.error.upload-submit",
    node: "dashboard",
    route: "/dashboard",
    selector: "body",
    action: "none",
    risk: "mutating",
    mockFailure: "dashboard-upload-submit",
    before: [
      { selector: "[data-testid='dashboard-open-upload-panel']" },
      { selector: "[data-testid='dashboard-upload-file-input']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
    ],
    expect: { text: /Graph forced dashboard upload submit failure/i, failedResponsePath: "/api/dashboard/upload" },
  },
  {
    id: "dashboard.error.upload-quota-paywall",
    node: "dashboard",
    route: "/dashboard",
    selector: "body",
    action: "none",
    risk: "mutating",
    mockFailure: "dashboard-upload-quota",
    before: [
      { selector: "[data-testid='dashboard-open-upload-panel']" },
      { selector: "[data-testid='dashboard-upload-file-input']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
    ],
    expect: { testId: "extraction-paywall-modal", text: /Upgrade|required|Pro/i, failedResponsePath: "/api/dashboard/upload" },
  },
  {
    id: "dashboard.error.chat",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='dashboard-chat-submit']",
    risk: "mutating",
    mockFailure: "dashboard-chat",
    before: [
      { selector: "[data-testid='dashboard-chat-toggle']" },
      { selector: "[data-testid='dashboard-chat-input']", action: "fill", value: "What should I do next?" },
    ],
    expect: { testId: "dashboard-chat-messages", text: /Graph forced dashboard chat failure/i, failedResponsePath: "/api/chat" },
  },
  {
    id: "dashboard.error.form-fill-extract",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='form-filler-submit']",
    risk: "mutating",
    mockFailure: "dashboard-form-fill-extract",
    before: [
      { selector: "[data-testid='dashboard-chat-toggle']" },
      { selector: "[data-testid='chat-mode-form-filler']" },
      { selector: "[data-testid='form-filler-file-input']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
    ],
    expect: { testId: "dashboard-chat-messages", text: /Graph forced form-fill extract failure/i, failedResponsePath: "/api/form-fill/extract" },
  },
  {
    id: "dashboard.error.form-fill-generate",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='form-preview-generate']",
    risk: "mutating",
    mockFailure: "dashboard-form-fill-generate",
    before: [
      { selector: "[data-testid='dashboard-chat-toggle']" },
      { selector: "[data-testid='chat-mode-form-filler']" },
      { selector: "[data-testid='form-filler-file-input']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] },
      { selector: "[data-testid='form-filler-submit']" },
      { selector: "[data-testid='form-preview-card']", action: "waitForSelector" },
    ],
    expect: { testId: "dashboard-chat-messages", text: /Graph forced form-fill generate failure/i, failedResponsePath: "/api/form-fill/generate" },
  },
  {
    id: "services.error.load",
    node: "services",
    route: "/services",
    selector: "body",
    action: "none",
    risk: "safe",
    mockFailure: "services-list",
    expect: { text: /Graph forced services list failure/i, failedResponsePath: "/api/marketplace/products" },
  },
  {
    id: "service-detail.error.load",
    node: "service-detail",
    route: "/services/fbar_check",
    selector: "body",
    action: "none",
    risk: "safe",
    mockFailure: "service-detail",
    expect: { text: /Graph forced service detail failure/i, failedResponsePath: "/api/marketplace/products/fbar_check" },
  },
  {
    id: "service-detail.error.start-order",
    node: "service-detail",
    route: "/services/fbar_check",
    selector: "[data-testid='service-start-fbar_check']",
    risk: "mutating",
    mockFailure: "service-start-order",
    expect: { text: /Graph forced service start order failure/i, failedResponsePath: "/api/marketplace/orders" },
  },
  {
    id: "service-questionnaire.error.load",
    node: "service-questionnaire",
    route: "/services/opt_execution/questionnaire",
    selector: "body",
    action: "none",
    risk: "safe",
    mockFailure: "questionnaire-load",
    expect: { text: /Graph forced questionnaire load failure/i, failedResponsePath: "/api/marketplace/products/opt_execution" },
  },
  {
    id: "service-questionnaire.error.evaluate",
    node: "service-questionnaire",
    route: "/services/opt_execution/questionnaire",
    selector: "[data-testid='service-questionnaire-evaluate']",
    risk: "mutating",
    mockFailure: "questionnaire-evaluate",
    expect: { text: /Graph forced questionnaire evaluate failure/i, failedResponsePath: "/api/marketplace/products/opt_execution/questionnaire" },
  },
  {
    id: "service-questionnaire.error.order",
    node: "service-questionnaire",
    route: "/services/opt_execution/questionnaire",
    selector: "[data-testid='service-questionnaire-continue']",
    risk: "mutating",
    mockFailure: "questionnaire-order",
    before: [
      { selector: "[data-testid='service-questionnaire-evaluate']" },
      { selector: "[data-testid='service-questionnaire-mode-execution']" },
    ],
    expect: { text: /Graph forced questionnaire order failure/i, failedResponsePath: "/api/marketplace/orders" },
  },
  {
    id: "find-lawyer.error.prefill",
    node: "find-lawyer",
    route: "/find-lawyer?case_id=case-graph",
    selector: "body",
    action: "none",
    risk: "safe",
    mockFailure: "find-lawyer-prefill",
    expect: { text: /Couldn't load your discovery answers/i, failedResponsePath: "/api/cases/case-graph/draft-brief" },
  },
  {
    id: "find-lawyer.error.submit",
    node: "find-lawyer",
    route: "/find-lawyer",
    selector: "[data-testid='find-lawyer-submit']",
    risk: "mutating",
    mockProfile: "professional-search",
    mockFailure: "find-lawyer-submit",
    before: [
      { selector: "[data-testid='find-lawyer-purpose']", action: "fill", value: "H-1B attorney shortlist" },
      { selector: "[data-testid='find-lawyer-brief']", action: "fill", value: "I need an immigration attorney for an H-1B transfer with prior F-1 OPT history, a pending employer timeline, wage-level questions, and a need to compare boutique and startup-focused firms. The case includes travel timing, document review, and communication with a fast-moving employer. I want verified firms with clear federal immigration experience and transparent fee ranges." },
    ],
    expect: { text: /Graph forced professional search submit failure/i, failedResponsePath: "/api/professional-search" },
  },
  {
    id: "find-lawyer-status.error.load",
    node: "find-lawyer-status",
    route: "/find-lawyer/search-complete",
    selector: "body",
    action: "none",
    risk: "safe",
    mockFailure: "professional-search-status",
    expect: { text: /Graph forced professional search status failure/i, failedResponsePath: "/api/professional-search/search-complete" },
  },
  {
    id: "find-lawyer-status.error.track-top-3",
    node: "find-lawyer-status",
    route: "/find-lawyer/search-paid",
    selector: "[data-testid='find-lawyer-track-top-3']",
    risk: "mutating",
    mockProfile: "professional-search",
    mockFailure: "professional-search-track",
    expect: { testId: "find-lawyer-status-error", text: /Graph forced professional search track failure/i, failedResponsePath: "/api/cases/case-graph/engagements" },
  },
  {
    id: "find-lawyer-status.error.download-pdf",
    node: "find-lawyer-status",
    route: "/find-lawyer/search-paid",
    selector: "[data-testid='find-lawyer-report-download-pdf']",
    risk: "safe",
    mockProfile: "professional-search",
    mockFailure: "professional-search-download",
    expect: { text: /Graph forced professional search download failure/i, failedResponsePath: "/api/professional-search/search-paid/download" },
  },
  {
    id: "find-lawyer-paid.error.poll",
    node: "find-lawyer-paid",
    route: "/find-lawyer/search-paid/paid?session_id=cs_graph",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "professional-search",
    mockFailure: "professional-search-paid",
    expect: { text: /Graph forced professional search paid failure/i, failedResponsePath: "/api/professional-search/search-paid" },
  },
  {
    id: "case.error.load",
    node: "case",
    route: "/case/case-graph",
    selector: "body",
    action: "none",
    risk: "safe",
    mockFailure: "case-load",
    expect: { text: /Case not available/i, failedResponsePath: "/api/cases/case-graph" },
  },
  {
    id: "case.error.gmail-connect",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-gmail-connect']",
    risk: "safe",
    mockProfile: "case",
    mockFailure: "case-gmail-connect",
    expect: { testId: "case-gmail-error", text: /Graph forced Gmail connect failure/i, failedResponsePath: "/api/auth/google/connect-gmail/url" },
  },
  {
    id: "case.error.gmail-sync",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-gmail-sync']",
    risk: "safe",
    mockProfile: "case",
    mockFailure: "case-gmail-sync",
    expect: { testId: "case-gmail-error", text: /Graph forced Gmail sync failure/i, failedResponsePath: "/api/auth/me/gmail/sync" },
  },
  {
    id: "case.error.gmail-disconnect",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-gmail-disconnect']",
    risk: "mutating",
    mockProfile: "case-gmail-connected",
    mockFailure: "case-gmail-disconnect",
    dialogAction: "accept",
    expect: { testId: "case-gmail-error", text: /Graph forced Gmail disconnect failure/i, failedResponsePath: "/api/auth/me/gmail/disconnect" },
  },
  {
    id: "case.error.engagement-add",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-engagement-add-submit']",
    risk: "mutating",
    mockProfile: "case",
    mockFailure: "case-engagement-add",
    before: [
      { selector: "[data-testid='case-engagement-add-open']" },
      { selector: "[data-testid='case-engagement-new-name']", action: "fill", value: "Graph Failed Firm" },
    ],
    expect: { testId: "case-engagement-error", text: /Graph forced case engagement failure/i, failedResponsePath: "/api/cases/case-graph/engagements" },
  },
  {
    id: "case.error.lawyer-track",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-lawyers-track-graph-immigration-llp']",
    risk: "mutating",
    mockProfile: "case",
    mockFailure: "professional-search-track",
    expect: { testId: "case-lawyers-track-error", text: /Graph forced professional search track failure/i, failedResponsePath: "/api/cases/case-graph/engagements" },
  },
  {
    id: "case.error.engagement-update",
    node: "case",
    route: "/case/case-graph",
    selector: "body",
    action: "none",
    risk: "mutating",
    mockProfile: "case-engagements",
    mockFailure: "case-engagement-update",
    before: [{ selector: "[data-testid='case-engagement-status-engagement-graph']", action: "select", value: "in_discussion" }],
    expect: { testId: "case-engagement-row-error-engagement-graph", text: /Graph forced case engagement update failure/i, failedResponsePath: "/api/cases/case-graph/engagements/engagement-graph" },
  },
  {
    id: "case.error.engagement-delete",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-engagement-delete-engagement-graph']",
    risk: "mutating",
    mockProfile: "case-engagements",
    mockFailure: "case-engagement-delete",
    dialogAction: "accept",
    expect: { testId: "case-engagement-row-error-engagement-graph", text: /Graph forced case engagement delete failure/i, failedResponsePath: "/api/cases/case-graph/engagements/engagement-graph" },
  },
  {
    id: "case.error.engagement-draft-email",
    node: "case",
    route: "/case/case-graph",
    selector: "[data-testid='case-engagement-email-engagement-graph']",
    risk: "safe",
    mockProfile: "case-engagements",
    mockFailure: "case-engagement-draft-email",
    expect: { testId: "case-engagement-row-error-engagement-graph", text: /Graph forced case engagement email failure/i, failedResponsePath: "/api/cases/case-graph/engagements/engagement-graph/draft-email" },
  },
  {
    id: "attorney.error.dashboard",
    node: "attorney",
    route: "/attorney/dashboard",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "attorney",
    mockFailure: "attorney-dashboard",
    expect: { text: /Graph forced attorney dashboard failure/i, failedResponsePath: "/api/attorney/dashboard" },
  },
  {
    id: "attorney.error.case-load",
    node: "attorney",
    route: "/attorney/cases/order-opt-intake-complete",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "attorney",
    mockFailure: "attorney-case",
    expect: { text: /Graph forced attorney case failure/i, failedResponsePath: "/api/attorney/cases/order-opt-intake-complete" },
  },
  {
    id: "attorney.error.review",
    node: "attorney",
    route: "/attorney/cases/order-opt-intake-complete",
    selector: "[data-testid='attorney-case-approve-review']",
    risk: "mutating",
    mockProfile: "attorney",
    mockFailure: "attorney-review",
    before: [
      { selector: "[data-testid='attorney-checklist-identity']" },
      { selector: "[data-testid='attorney-checklist-eligibility']" },
      { selector: "[data-testid='attorney-case-notes']", action: "fill", value: "Graph review notes" },
    ],
    expect: { text: /Graph forced attorney review failure/i, failedResponsePath: "/api/attorney/cases/order-opt-intake-complete/review" },
  },
  {
    id: "account-orders.error.load",
    node: "account-orders",
    route: "/account/orders",
    selector: "body",
    action: "none",
    risk: "safe",
    mockFailure: "account-orders",
    expect: { text: /Graph forced account orders failure/i, failedResponsePath: "/api/marketplace/orders" },
  },
  {
    id: "order-detail.error.load",
    node: "account-order-detail",
    route: "/account/orders/order-83b-draft",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "order-detail",
    mockFailure: "order-detail",
    expect: { text: /Graph forced order detail failure/i, failedResponsePath: "/api/marketplace/orders/order-83b-draft" },
  },
  {
    id: "order-detail.error.pull-prefill",
    node: "account-order-detail",
    route: "/account/orders/order-83b-draft",
    selector: "[data-testid='order-detail-pull-prefill']",
    risk: "mutating",
    mockProfile: "order-detail",
    mockFailure: "order-prefill",
    expect: { text: /Graph forced order prefill failure/i, failedResponsePath: "/api/marketplace/orders/order-83b-draft/pull-extracted-info" },
  },
  {
    id: "order-detail.error.save-intake",
    node: "account-order-detail",
    route: "/account/orders/order-83b-draft",
    selector: "[data-testid='order-detail-save-intake']",
    risk: "mutating",
    mockProfile: "order-detail",
    mockFailure: "order-save-intake",
    before: [
      { selector: "[data-testid='order-83b-taxpayer-name']", action: "fill", value: "Jessica Chen" },
      { selector: "[data-testid='order-83b-taxpayer-address']", action: "fill", value: "123 Startup Way, San Francisco, CA" },
      { selector: "[data-testid='order-83b-company-name']", action: "fill", value: "GraphCo, Inc." },
      { selector: "[data-testid='order-83b-grant-date']", action: "fill", value: "2026-04-01" },
      { selector: "[data-testid='order-83b-property-description']", action: "fill", value: "Restricted common stock" },
      { selector: "[data-testid='order-83b-share-count']", action: "fill", value: "10000" },
      { selector: "[data-testid='order-83b-fmv']", action: "fill", value: "0.02" },
      { selector: "[data-testid='order-83b-exercise-price']", action: "fill", value: "0.01" },
      { selector: "[data-testid='order-83b-vesting-schedule']", action: "fill", value: "25% after 12 months, monthly thereafter" },
    ],
    expect: { text: /Graph forced order intake failure/i, failedResponsePath: "/api/marketplace/orders/order-83b-draft/intake" },
  },
  {
    id: "order-detail.error.run-now",
    node: "account-order-detail",
    route: "/account/orders/order-83b-ready",
    selector: "[data-testid='order-detail-run-now']",
    risk: "mutating",
    mockProfile: "order-detail",
    mockFailure: "order-process",
    expect: { text: /Graph forced order process failure/i, failedResponsePath: "/api/marketplace/orders/order-83b-ready/process" },
  },
  {
    id: "order-detail.error.mark-mailed",
    node: "account-order-detail",
    route: "/account/orders/order-83b-result",
    selector: "[data-testid='order-detail-mark-mailed']",
    risk: "mutating",
    mockProfile: "order-detail",
    mockFailure: "order-mark-mailed",
    before: [{ selector: "[data-testid='order-detail-tracking-number']", action: "fill", value: "9407100000000000123456" }],
    expect: { text: /Graph forced order mark mailed failure/i, failedResponsePath: "/api/marketplace/orders/order-83b-result/mark-mailed" },
  },
  {
    id: "order-agreement.error.load",
    node: "account-order-agreement",
    route: "/account/orders/order-opt-intake-complete/agreement",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "order-detail",
    mockFailure: "agreement-load",
    expect: { text: /Graph forced agreement load failure/i, failedResponsePath: "/api/marketplace/orders/order-opt-intake-complete/agreement" },
  },
  {
    id: "order-agreement.error.sign",
    node: "account-order-agreement",
    route: "/account/orders/order-opt-intake-complete/agreement",
    selector: "[data-testid='order-agreement-sign']",
    risk: "mutating",
    mockProfile: "order-detail",
    mockFailure: "agreement-sign",
    before: [
      { selector: "[data-testid='order-agreement-text']", action: "scrollToBottom" },
      { selector: "[data-testid='order-agreement-signature']", action: "fill", value: "Jessica Chen" },
    ],
    expect: { text: /Graph forced agreement sign failure/i, failedResponsePath: "/api/marketplace/orders/order-opt-intake-complete/sign-agreement" },
  },
  {
    id: "form8843.error.generate",
    node: "form8843",
    route: "/form-8843",
    selector: "[data-testid='form8843-wizard-generate']",
    risk: "mutating",
    mockProfile: "form8843",
    mockFailure: "form8843-generate",
    before: [
      { selector: "[data-testid='form8843-field-full_name']", action: "fill", value: "Jessica Chen" },
      { selector: "[data-testid='form8843-wizard-continue']" },
      { selector: "[data-testid='form8843-field-arrival_date']", action: "fill", value: "2024-08-20" },
      { selector: "[data-testid='form8843-wizard-continue']" },
      { selector: "[data-testid='form8843-field-school_name']", action: "fill", value: "Columbia University" },
      { selector: "[data-testid='form8843-wizard-continue']" },
      { selector: "[data-testid='form8843-field-citizenship_country']", action: "fill", value: "China" },
      { selector: "[data-testid='form8843-wizard-continue']" },
      { selector: "[data-testid='form8843-field-2025']", action: "fill", value: "120" },
      { selector: "[data-testid='form8843-field-2024']", action: "fill", value: "90" },
      { selector: "[data-testid='form8843-wizard-continue']" },
    ],
    expect: { text: /Graph forced Form 8843 generate failure/i, failedResponsePath: "/api/form8843/generate" },
  },
  {
    id: "form8843-success.error.load",
    node: "form8843-success",
    route: "/form-8843/success?orderId=form8843-order",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "form8843",
    mockFailure: "form8843-success",
    expect: { text: /Graph forced Form 8843 success failure/i, failedResponsePath: "/api/form8843/orders/form8843-order" },
  },
  {
    id: "form8843-success.error.download",
    node: "form8843-success",
    route: "/form-8843/success?orderId=form8843-order",
    selector: "[data-testid='form8843-success-download']",
    risk: "safe",
    mockProfile: "form8843",
    mockFailure: "form8843-download",
    expect: { text: /Graph forced Form 8843 download failure/i, failedResponsePath: "/api/form8843/orders/form8843-order/pdf" },
  },
  {
    id: "form8843-success.error.mark-mailed",
    node: "form8843-success",
    route: "/form-8843/success?orderId=form8843-order",
    selector: "[data-testid='form8843-mark-mailed']",
    risk: "mutating",
    mockProfile: "form8843",
    mockFailure: "form8843-mark-mailed",
    before: [{ selector: "[data-testid='form8843-mailing-tracking']", action: "fill", value: "9407100000000000123456" }],
    expect: { text: /Graph forced Form 8843 mark mailed failure/i, failedResponsePath: "/api/form8843/orders/form8843-order/mark-mailed" },
  },
  {
    id: "check.student.error.create",
    node: "check-intake",
    route: "/check/student",
    selector: "[data-testid='student-intake-continue']",
    risk: "mutating",
    mockProfile: "check",
    mockFailure: "check-create",
    before: [
      { selector: "[data-testid='student-intake-student_status-enrolled_cpt']" },
      { selector: "[data-testid='student-intake-has_cpt_authorization-yes']" },
      { selector: "[data-testid='student-intake-cpt_fulltime_months-1-6']" },
      { selector: "[data-testid='student-intake-income_reporting-sprintax']" },
      { selector: "[data-testid='student-intake-planning_travel-no']" },
    ],
    expect: { testId: "student-intake-error", text: /Graph forced check create failure/i, failedResponsePath: "/api/checks" },
  },
  {
    id: "check.entity.error.create",
    node: "check-intake",
    route: "/check/entity",
    selector: "[data-testid='entity-intake-continue']",
    risk: "mutating",
    mockProfile: "check",
    mockFailure: "check-create",
    before: [
      { selector: "[data-testid='entity-intake-entity_type-smllc']" },
      { selector: "[data-testid='entity-intake-owner_residency-on_visa']" },
      { selector: "[data-testid='entity-intake-visa_type-f1_opt_stem']" },
      { selector: "[data-testid='entity-intake-state-of-formation']", action: "fill", value: "Delaware" },
      { selector: "[data-testid='entity-intake-separate_bank_account-yes']" },
      { selector: "[data-testid='entity-intake-foreign_capital_transfer-no']" },
      { selector: "[data-testid='entity-intake-formation_age-this_year']" },
      { selector: "[data-testid='entity-intake-tax_software_used-sprintax']" },
    ],
    expect: { testId: "entity-intake-error", text: /Graph forced check create failure/i, failedResponsePath: "/api/checks" },
  },
  {
    id: "check.stem.error.create",
    node: "check-intake",
    route: "/check/stem-opt",
    selector: "[data-testid='stem-intake-continue']",
    risk: "mutating",
    mockProfile: "check",
    mockFailure: "check-create",
    before: [
      { selector: "[data-testid='stem-intake-stage-stem_opt']" },
      { selector: "[data-testid='stem-intake-years']", action: "fill", value: "3" },
      { selector: "[data-testid='stem-intake-employment_status-employed']" },
      { selector: "[data-testid='stem-intake-employer_changed-no']" },
      { selector: "[data-testid='stem-intake-tax_software_used-sprintax']" },
    ],
    expect: { testId: "stem-intake-error", text: /Graph forced check create failure/i, failedResponsePath: "/api/checks" },
  },
  {
    id: "check.student.error.upload-load",
    node: "check-upload",
    route: "/check/student/upload?id=student-check",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "check",
    mockFailure: "check-upload-load",
    expect: { testId: "student-upload-error", text: /Graph forced check upload load failure/i, failedResponsePath: "/api/checks/student-check" },
  },
  {
    id: "check.student.error.upload-submit",
    node: "check-upload",
    route: "/check/student/upload?id=student-check",
    selector: "body",
    action: "none",
    risk: "mutating",
    mockProfile: "check",
    mockFailure: "check-upload-submit",
    before: [{ selector: "[data-testid='student-upload-input-i20']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] }],
    expect: { testId: "student-upload-error", text: /Graph forced check upload submit failure/i, failedResponsePath: "/api/checks/student-check/documents" },
  },
  {
    id: "check.entity.error.upload-submit",
    node: "check-upload",
    route: "/check/entity/upload?id=entity-check",
    selector: "body",
    action: "none",
    risk: "mutating",
    mockProfile: "check",
    mockFailure: "check-upload-submit",
    before: [{ selector: "[data-testid='entity-upload-input-tax-return']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] }],
    expect: { testId: "entity-upload-error", text: /Graph forced check upload submit failure/i, failedResponsePath: "/api/checks/entity-check/documents" },
  },
  {
    id: "check.stem.error.upload-submit",
    node: "check-upload",
    route: "/check/stem-opt/upload?id=stem-check",
    selector: "body",
    action: "none",
    risk: "mutating",
    mockProfile: "check",
    mockFailure: "check-upload-submit",
    before: [{ selector: "[data-testid='stem-upload-input-employment_letter']", action: "setInputFiles", files: ["tests/fixtures/graph-document.pdf"] }],
    expect: { testId: "stem-upload-error", text: /Graph forced check upload submit failure/i, failedResponsePath: "/api/checks/stem-check/documents" },
  },
  {
    id: "check.student.error.review-extract",
    node: "check-review",
    route: "/check/student/review?id=student-check",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "check",
    mockFailure: "check-review-extract",
    expect: { text: /Graph forced check review extract failure/i, failedResponsePath: "/api/checks/student-check/extract" },
  },
  {
    id: "share.error.load",
    node: "share",
    route: "/share/share-token",
    selector: "body",
    action: "none",
    risk: "safe",
    mockProfile: "share",
    mockFailure: "share-load",
    expect: { text: /Graph forced share load failure/i, failedResponsePath: "/api/share/share-token" },
  },
  {
    id: "dashboard.payment.checkout",
    node: "dashboard",
    route: "/dashboard",
    selector: "[data-testid='checkout-submit']",
    risk: "payment",
    defaultRun: false,
  },
];

export function graphEdgesForDefaultRun() {
  return graphEdges.filter((edge) => (
    edge.defaultRun !== false
    && edge.risk !== "payment"
    && edge.risk !== "voice"
    && edge.risk !== "external"
  ));
}
