"""Anthropic-powered runner for professional search.

Drives a `ProfessionalSearchRequestRow` to completion:

1. Loads the personas for the request's vertical.
2. For each persona in parallel: builds a prompt (methodology + persona
   instructions + case brief), calls Claude with the `web_search`
   server-side tool and adaptive thinking, parses the returned YAML,
   and writes it to a persona-specific output path.
3. Merges all persona YAMLs into the diligence DB via
   `professional_search.ingest.ingest_docs`.
4. Renders a tier report from `v_attorney_comparison` / `v_vendor_comparison`
   and stores it on the request row.

The runner is designed to be invoked from FastAPI `BackgroundTasks`:

    background_tasks.add_task(run_search_sync, request_id)

Errors are captured onto the request row rather than raised so the
status-polling endpoint can surface them to the UI.
"""
from __future__ import annotations

import asyncio
import datetime as _dt
import logging
import re
from pathlib import Path

import anthropic
import httpx
import yaml
from sqlalchemy.orm import Session

from compliance_os.professional_search.db import (
    attorney_comparison,
    connect as connect_diligence,
    init_schema as init_diligence_schema,
    vendor_comparison,
)
from compliance_os.professional_search.ingest import ingest_docs
from compliance_os.professional_search.personas import (
    Persona,
    build_prompt,
    list_personas,
)
from compliance_os.settings import settings
from compliance_os.web.models.database import get_engine
from compliance_os.web.models.tables import ProfessionalSearchRequestRow

logger = logging.getLogger(__name__)

# Plain server-side web search. We deliberately use the older
# `web_search_20250305` rather than `web_search_20260209`:
#
# - _20260209 enables "dynamic filtering", which runs code-execution
#   server-side to filter results before they reach context. That adds
#   latency we don't need (our use case is synthesis, not result
#   filtering) and — more importantly — breaks our pause_turn retry
#   loop with a 400: "container_id is required when there are pending
#   tool uses generated by code execution with tools." We'd have to
#   thread container_id through every retry to make it work.
# - _20250305 is plain search: URL results returned directly, no
#   container, no filtering loop. Simpler, faster, no retry bug.
WEB_SEARCH_TOOL = {"type": "web_search_20250305", "name": "web_search"}

# Cap the per-persona agentic loop — prevents runaway when the model
# keeps chaining web searches without settling. One pass = up to 10
# web_search iterations server-side; 2 retries gives us up to 30 total
# iterations which is plenty for 6-firm discovery at medium effort.
MAX_PAUSE_TURN_RETRIES = 2

# Hard per-persona wall-clock ceiling so one runaway call can't block the
# whole request forever. With Sonnet 4.6 + medium effort + target=6 firms,
# a healthy persona finishes in ~2–4 min. 10 min is the bail-out.
PER_PERSONA_TIMEOUT_S = 600


# ---------------------------------------------------------------------
# Progress updates — write per-persona status to the DB as work happens
# ---------------------------------------------------------------------

def _update_persona_status(request_id: str, persona_id: str, status: dict) -> None:
    """Atomically merge a per-persona status slot into the request row.

    Concurrent personas all call this from the same asyncio event loop.
    Read-modify-write on a JSON column would race: persona A reads at
    T1, persona B reads at T1, both write at T2, last write wins and
    one persona's status is silently dropped.

    Fix:
    - **Postgres (prod)**: `with_for_update()` emits `SELECT ... FOR
      UPDATE`, taking a real row lock for the duration of `db.begin()`.
      Other writers block until commit.
    - **SQLite (local dev)**: `with_for_update()` is a no-op — pysqlite
      doesn't translate it. The lost-update race is prevented in
      practice because all persona coroutines run on a single asyncio
      event loop and `_update_persona_status` is a synchronous DB call
      (no `await` between the SELECT and the COMMIT inside `db.begin()`),
      so cooperative scheduling can't interleave them. If we ever move
      this to a thread pool / true parallelism, the SQLite path would
      need `BEGIN IMMEDIATE` via a SQLAlchemy event hook.
    """
    from sqlalchemy import select

    try:
        engine = get_engine()
        with Session(engine) as db:
            with db.begin():
                row = db.execute(
                    select(ProfessionalSearchRequestRow)
                    .where(ProfessionalSearchRequestRow.id == request_id)
                    .with_for_update()
                ).scalar_one_or_none()
                if row is None:
                    return
                current = dict(row.persona_status or {})
                current[persona_id] = status
                row.persona_status = current
                # Commit happens automatically when `with db.begin()` exits.
    except Exception:
        logger.exception("failed to update persona_status for %s/%s", request_id, persona_id)


# ---------------------------------------------------------------------
# YAML parsing from model output
# ---------------------------------------------------------------------

_YAML_FENCE_RE = re.compile(r"```ya?ml\s*\n(.*?)\n```", re.DOTALL)


def _extract_yaml(text: str) -> dict:
    """Pull a YAML doc out of the assistant's text.

    Prefers a fenced ```yaml block; falls back to the whole body if no
    fence is present. Raises ValueError if nothing parseable is found.
    """
    m = _YAML_FENCE_RE.search(text)
    body = m.group(1) if m else text
    doc = yaml.safe_load(body)
    if not isinstance(doc, dict):
        raise ValueError(f"Expected YAML mapping, got {type(doc).__name__}")
    if "firms" not in doc:
        raise ValueError("YAML missing required 'firms' key")
    return doc


# ---------------------------------------------------------------------
# Claude call
# ---------------------------------------------------------------------

async def _run_persona(
    client: anthropic.AsyncAnthropic,
    persona: Persona,
    *,
    request_id: str,
    case_brief: str,
    purpose: str,
    output_path: Path,
    methodology_system_block: list[dict],
) -> dict:
    """Run one persona's search end-to-end. Returns a status dict.

    Side effect: writes incremental status ('running', then terminal)
    to the DB so the frontend poller can show live progress.
    """
    started_at = _dt.datetime.utcnow().isoformat()
    prompt = build_prompt(
        persona,
        case_brief=case_brief,
        purpose=purpose,
        output_path=output_path,
    )

    _update_persona_status(
        request_id, persona.id,
        {"status": "running", "started_at": started_at},
    )

    async def _call() -> dict:
        messages: list[dict] = [{"role": "user", "content": prompt}]
        retries = 0
        while True:
            logger.info("persona %s: opening stream (retry=%d)", persona.id, retries)
            async with client.messages.stream(
                model=settings.search_model,
                max_tokens=16000,
                thinking={"type": "adaptive"},
                output_config={"effort": settings.search_effort},
                system=methodology_system_block,
                tools=[WEB_SEARCH_TOOL],
                messages=messages,
            ) as stream:
                response = await stream.get_final_message()
            logger.info(
                "persona %s: stop_reason=%s input=%d output=%d cache_read=%d",
                persona.id, response.stop_reason,
                response.usage.input_tokens, response.usage.output_tokens,
                getattr(response.usage, "cache_read_input_tokens", 0),
            )

            if response.stop_reason == "pause_turn":
                if retries >= MAX_PAUSE_TURN_RETRIES:
                    raise RuntimeError(
                        f"persona {persona.id}: pause_turn loop exceeded "
                        f"{MAX_PAUSE_TURN_RETRIES} retries"
                    )
                retries += 1
                messages = [
                    {"role": "user", "content": prompt},
                    {"role": "assistant", "content": response.content},
                ]
                continue
            break

        text_parts = [b.text for b in response.content if b.type == "text"]
        full_text = "\n\n".join(text_parts)

        doc = _extract_yaml(full_text)
        doc.setdefault("agent", persona.id)
        doc.setdefault("vertical", persona.vertical)
        doc.setdefault("purpose", purpose)

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(yaml.safe_dump(doc, sort_keys=False))

        return {
            "status": "complete",
            "output_path": str(output_path),
            "firm_count": len(doc.get("firms") or []),
            "started_at": started_at,
            "finished_at": _dt.datetime.utcnow().isoformat(),
            "cache_read_tokens": getattr(response.usage, "cache_read_input_tokens", 0),
            "cache_write_tokens": getattr(response.usage, "cache_creation_input_tokens", 0),
            "input_tokens": response.usage.input_tokens,
            "output_tokens": response.usage.output_tokens,
        }

    try:
        result = await asyncio.wait_for(_call(), timeout=PER_PERSONA_TIMEOUT_S)
    except asyncio.TimeoutError:
        logger.error("persona %s: timed out after %ds", persona.id, PER_PERSONA_TIMEOUT_S)
        result = {
            "status": "failed",
            "error": f"timed out after {PER_PERSONA_TIMEOUT_S}s — try a narrower case brief or lower effort",
            "started_at": started_at,
            "finished_at": _dt.datetime.utcnow().isoformat(),
        }
    except Exception as exc:
        logger.exception("persona %s failed", persona.id)
        result = {
            "status": "failed",
            "error": f"{type(exc).__name__}: {exc}",
            "started_at": started_at,
            "finished_at": _dt.datetime.utcnow().isoformat(),
        }

    _update_persona_status(request_id, persona.id, result)
    return result


# ---------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------

def _methodology_system_block() -> list[dict]:
    """System prompt = stable tier methodology (cached) + frame."""
    methodology = (
        Path(__file__).parents[2]
        / "professional_search"
        / "tier_methodology.md"
    ).read_text()
    return [
        {
            "type": "text",
            "text": (
                "You are a professional-search analyst helping a user find "
                "lawyers, CPAs, or bankers for their case. You always ground "
                "credential scoring in externally-verifiable signals per the "
                "methodology below. You use web_search liberally to verify "
                "Chambers rankings, AILA leadership, PACER filings, and "
                "third-party press. You never invent firms, and you never "
                "cite a firm's own marketing copy as a credential source."
            ),
        },
        {
            "type": "text",
            "text": methodology,
            "cache_control": {"type": "ephemeral"},
        },
    ]


async def _run_all_personas(
    personas: list[Persona],
    *,
    request_id: str,
    case_brief: str,
    purpose: str,
    output_dir: Path,
) -> dict[str, dict]:
    """Dispatch every persona in parallel. Per-persona status is committed
    to the DB as each persona starts and finishes; the returned dict is
    the final snapshot for the orchestrator."""

    # Explicit httpx client with a generous but finite timeout. The SDK's
    # default 10-minute cap was too short for Opus-4.7 + high-effort runs,
    # and asyncio.wait_for in _run_persona still enforces PER_PERSONA_TIMEOUT_S
    # as the hard wall-clock ceiling — this just prevents httpx from
    # dropping a still-live streaming connection mid-response.
    http_client = httpx.AsyncClient(timeout=httpx.Timeout(900.0, connect=15.0))
    client = anthropic.AsyncAnthropic(
        api_key=settings.anthropic_api_key,
        http_client=http_client,
        max_retries=1,
    )
    methodology = _methodology_system_block()

    async def one(p: Persona) -> tuple[str, dict]:
        path = output_dir / f"{p.id}.yaml"
        status = await _run_persona(
            client, p,
            request_id=request_id,
            case_brief=case_brief,
            purpose=purpose,
            output_path=path,
            methodology_system_block=methodology,
        )
        return p.id, status

    try:
        results = await asyncio.gather(*(one(p) for p in personas))
    finally:
        await http_client.aclose()
    return dict(results)


def run_search_sync(request_id: str) -> None:
    """Entry point for FastAPI BackgroundTasks.

    Opens its own SQLAlchemy session (BackgroundTasks don't get the
    request-scoped one) and drives the request row through
    queued → running → complete (or failed).
    """
    engine = get_engine()
    with Session(engine) as db:
        row = db.get(ProfessionalSearchRequestRow, request_id)
        if row is None:
            logger.error("search request %s not found", request_id)
            return

        row.status = "running"
        db.commit()

        try:
            personas = list_personas(row.vertical)
            output_dir = (
                settings.professional_search_output_dir
                / _dt.date.today().isoformat()
                / request_id
            )
            output_dir.mkdir(parents=True, exist_ok=True)

            # Brief that goes to every persona: user's case brief + any
            # text extracted from uploaded documents.
            enriched_brief = row.case_brief
            if row.uploaded_notes:
                enriched_brief += "\n\n=== Context from uploaded documents ===\n" + row.uploaded_notes

            if not settings.anthropic_api_key:
                raise RuntimeError(
                    "ANTHROPIC_API_KEY not set; cannot run professional search"
                )

            # Generate one extra "tuned" persona from the case brief
            # (Haiku, ~5s) and then dispatch all personas in parallel.
            # Both run inside a single `asyncio.run()` so we don't risk
            # event-loop teardown weirdness on uvloop / older runtimes
            # that can leave a partially-closed loop after the first
            # call. Tuner failure is silent — we fall back to canonicals.
            from compliance_os.web.services.persona_tuner import generate_tuned_persona

            async def _tune_then_dispatch() -> dict[str, dict]:
                tuned = await generate_tuned_persona(
                    enriched_brief, row.vertical, output_dir
                )
                personas_for_run = personas + ([tuned] if tuned is not None else [])
                if tuned is not None:
                    logger.info("dispatching with tuned persona: %s", tuned.id)
                return await _run_all_personas(
                    personas_for_run,
                    request_id=request_id,
                    case_brief=enriched_brief,
                    purpose=row.purpose,
                    output_dir=output_dir,
                )

            persona_status = asyncio.run(_tune_then_dispatch())
            # Re-read the row to pick up any concurrent writes from the
            # per-persona updaters before we set terminal state.
            db.refresh(row)

            # Ingest any persona that completed (don't fail the whole run
            # if one persona failed — the others may still be useful).
            yaml_paths = [
                s["output_path"]
                for s in persona_status.values()
                if s.get("status") == "complete" and s.get("output_path")
            ]
            if not yaml_paths:
                row.status = "failed"
                row.error = "All personas failed — see persona_status for details"
                row.completed_at = _dt.datetime.utcnow()
                db.commit()
                return

            init_diligence_schema()
            ingest_docs(yaml_paths)

            # Persist the full per-firm data (rationales, credentials,
            # sources) on the row. The HTML/PDF report renders from this
            # column, so reports stay reproducible even if the on-disk
            # YAMLs are later lost or moved.
            try:
                # Direct import from the aggregator package — avoids a
                # service→router back-edge that would create a circular
                # dependency and break if the router is ever split.
                from compliance_os.professional_search.aggregator import (
                    aggregate_firms,
                    load_persona_yamls,
                )
                yamls = load_persona_yamls(row)
                aggregated = aggregate_firms(yamls)
                logger.info(
                    "firms_data persistence: %d personas, %d unique firms",
                    len(yamls), len(aggregated),
                )
                row.firms_data = aggregated
                db.commit()
                logger.info("firms_data persistence: committed")
            except Exception:
                # A failure here must not poison the outer session — without
                # an explicit rollback the next db.commit() (for tier_report)
                # would error with "current transaction is aborted".
                db.rollback()
                logger.exception("failed to persist firms_data; report may be sparse")

            with connect_diligence() as dconn:
                if row.vertical.startswith("immigration") or row.vertical.endswith("attorney") or row.vertical == "attorney":
                    rows = attorney_comparison(dconn)
                else:
                    # Map vertical key to vendor_type used in diligence DB
                    vendor_type_map = {
                        "cpa": "cpa",
                        "bank": "bank",
                        "caa": "caa",
                    }
                    vt = vendor_type_map.get(row.vertical, None)
                    rows = vendor_comparison(dconn, vendor_type=vt)

            # Filter to just this run's purpose so re-runs don't pollute.
            rows = [r for r in rows if r.get("purpose") == row.purpose]

            row.tier_report = rows
            row.status = "complete"
            row.completed_at = _dt.datetime.utcnow()
            db.commit()

        except Exception as exc:
            logger.exception("search request %s failed", request_id)
            row.status = "failed"
            row.error = f"{type(exc).__name__}: {exc}"
            row.completed_at = _dt.datetime.utcnow()
            db.commit()
